/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "e84262a9688ac262ddbc222a04481c4e3ce2baf4"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
